### ISSUE TITLE
add missing crate

### ISSUE THREAD

**Issue by falkben** [falkben/cratonomics#9]
- Fall 2018 Crate

**Comment by oyavri** [comment]
Can I get this one?

**Comment by oyavri** [comment]
Umm I can't find any information about price. Where should I look for?

**Comment by falkben** [comment]
https://pubg.gamepedia.com/Crates/PC/Fall_2018_Crate is one place, though I like to use the official pubg updates

**Comment by falkben** [comment]
One trick to make sure of is making sure the name is actually valid in the steam marketplace (including capitalization) -- sometimes they differ from what's listed on the announcement page.  you can check by requesting pricing data through the API or by just testing the link, like so: https://steamcommunity.com/market/listings/578080/Survivalist%20Slacks

**Comment by oyavri** [comment]
I've learned that this crate can be purchased with BP and also no key required to open it. Search for Skin & Items [here](https://steamcommunity.com/games/578080/announcements/detail/1688177728620125512). And there's no listing for that crate on market
